export default {
  CLEAR_ALL: 'BOOKS/CLEAR_ALL',
  CREATE: 'BOOKS/CREATE',
  DELETE_BY_AUTHOR: 'BOOKS/DELETE_BY_AUTHOR',
  DELETE: 'BOOKS/DELETE',
  FETCH: 'BOOKS/FETCH',
  REQUEST_END: 'BOOKS/REQUEST_END',
  REQUEST_START: 'BOOKS/REQUEST_START',
  UPDATE: 'BOOKS/UPDATE',
}
