export const AUTH = {
  LOGIN: 'AUTH_LOGIN',
  LOGOUT: 'AUTH_LOGOUT',
  REQUEST_END: 'AUTH_REQUEST_END',
  REQUEST_START: 'AUTH_REQUEST_START',
  VERIFICATION_EMAIL_SENT: 'AUTH_VERIFICATION_EMAIL_SENT',
};
