export const AUTHORS = {
  REQUEST_START: 'AUTHORS_REQUEST_START',
  REQUEST_END: 'AUTHORS_REQUEST_END',
  FETCH_SUCCESS: 'AUTHORS_FETCH_SUCCESS',
  CREATE_SUCCESS: 'AUTHORS_CREATE_SUCCESS',
  UPDATE_SUCCESS: 'AUTHORS_UPDATE_SUCCESS',
  DELETE_SUCCESS: 'AUTHORS_DELETE_SUCCESS',
  CLEAR_ALL: 'AUTHORS_CLEAR_ALL',

  SET_PRESELECTED: 'SET_PRESELECTED',
  CLEAR_PRESELECTED: 'CLEAR_PRESELECTED',
};
