export const BOOKS = {
  REQUEST_START: 'BOOKS_REQUEST_START',
  REQUEST_END: 'BOOKS_REQUEST_END',
  FETCH_SUCCESS: 'BOOKS_FETCH_SUCCESS',
  CREATE_SUCCESS: 'BOOKS_CREATE_SUCCESS',
  UPDATE_SUCCESS: 'BOOKS_UPDATE_SUCCESS',
  DELETE_SUCCESS: 'BOOKS_DELETE_SUCCESS',
  DELETE_BY_AUTHOR_SUCCESS: 'BOOKS_DELETE_BY_AUTHOR_SUCCESS',
  CLEAR_ALL: 'BOOKS_CLEAR_ALL',
};
