export default {
  CLEAR_ALL: 'AUTHORS/CLEAR_ALL',
  CLEAR_PRESELECTED: 'AUTHORS/CLEAR_PRESELECTED',
  CREATE: 'AUTHORS/CREATE',
  DELETE: 'AUTHORS/DELETE',
  FETCH: 'AUTHORS/FETCH',
  REQUEST_END: 'AUTHORS/REQUEST_END',
  REQUEST_START: 'AUTHORS/REQUEST_START',
  SET_PRESELECTED: 'AUTHORS/SET_PRESELECTED',
  UPDATE: 'AUTHORS/UPDATE',
};
