export default {
  LOGIN: 'AUTH/LOGIN',
  LOGOUT: 'AUTH/LOGOUT',
  REQUEST_END: 'AUTH/REQUEST_END',
  REQUEST_START: 'AUTH/REQUEST_START',
  PASSWORD_RESET_EMAIL_SENT: 'AUTH/PASSWORD_RESET_EMAIL_SENT',
  VERIFICATION_EMAIL_SENT: 'AUTH/VERIFICATION_EMAIL_SENT',
};
